version: 2

sources:
  - name: f1_data
    database: f1_data_v2
    schema: main
    tables:
      - name: events
      - name: sessions
      - name: drivers
      - name: laps
      - name: car_data
      - name: locations
      - name: intervals
      - name: weather
      - name: race_control
      - name: session_status
      - name: track_status
      - name: team_radio
      - name: team_radio_files
      - name: team_radio_texts
      - name: ingestion_log
